name: Deploy Backend to AWS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del codigo
      uses: actions/checkout@v3

    - name: Configurar llave SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Desplegar en AWS EC2 via SSH (Usando Puente Publico)
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@3.90.234.57 "sudo docker stop api-ventas || true && sudo docker rm api-ventas || true && sudo docker run -d --name api-ventas -p 8080:8080 eclipse-temurin:17-jdk-alpine"
